In [1]:
# 1. Create an np array of 10 zeros
# 2. Create an np array of 10 ones
# 3. Create an np array of ints from 10 to 50
# 4. Create an np array of even integers from 10 to 50
# 5. Create a 3x3 matrix with numbers from 0 - 8
# 6. Generate an array of 10 random numbers from 0-1
# 7. Create a 1d np array and reshape it to be 2d
# 8. Get summ of all values in that array
# 9. Get the mean, standard deviation, variance in the array
# 10. Get the sum of all columns in that array

In [4]:
import numpy as np

In [34]:
# 1. Create an np array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
# 2. Create an np array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
# 3. Create an np array of ints from 10 to 50
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [38]:
# 4. Create an np array of even integers from 10 to 50
np.arange(10, 50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [41]:
# 5. Create a 3x3 matrix with numbers from 0 - 8
l = np.arange(0, 9)
l = l.reshape(3, 3)

In [22]:
# 6. Generate an array of 10 random numbers from 0-1
np.random.rand(10)

array([0.98093886, 0.60081609, 0.81396852, 0.70864515, 0.02753468,
       0.90426722, 0.44990485, 0.11892465, 0.83530018, 0.20224823])

In [23]:
# 7. Create a 1d np array and reshape it to be 2d
l = np.arange(0, 9)
l.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
# 8. Get sum of all values in that array
l.sum()

36

In [33]:
# 9. Get the mean, standard deviation, variance in the array
mean = l.mean() # np.mean(l)
mean

4.0

In [28]:
l.std()

2.581988897471611

In [29]:
l.var()

6.666666666666667

In [47]:
# 10. Get the sum of all columns in that array
l.sum(axis=0)

array([ 9, 12, 15])